/** Static content for the road games. */

export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "Washington DC" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

export const CA_PROVINCES: { code: string; name: string }[] = [
  { code: "BC", name: "British Columbia" },
  { code: "AB", name: "Alberta" },
  { code: "SK", name: "Saskatchewan" },
  { code: "MB", name: "Manitoba" },
  { code: "ON", name: "Ontario" },
  { code: "QC", name: "Quebec" },
  { code: "NB", name: "New Brunswick" },
  { code: "NS", name: "Nova Scotia" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "NL", name: "Newfoundland" },
  { code: "YT", name: "Yukon" },
  { code: "NT", name: "Northwest Terr." },
  { code: "NU", name: "Nunavut" },
];

/** Scavenger-hunt targets — first to spot it claims it. */
export const ROADSIDE_ITEMS: string[] = [
  "Wind turbine",
  "Lighthouse",
  "Surfer in a wetsuit",
  "Sea lion or seal",
  "Whale spout",
  "Redwood bigger than the car",
  "Elk or deer",
  "Cow traffic jam",
  "Hawk on a fence post",
  "Vineyard",
  "Roadside fruit stand",
  "Classic car (pre-1980)",
  "Convertible with the top down",
  "RV towing a car",
  "Mattress on a roof",
  "Speed trap (cop with radar)",
  "Hitchhiker",
  "Rest-stop dog",
  "Train crossing",
  "Ferry boat",
  "Drawbridge",
  "Tunnel",
  "State line sign",
  "Border crossing booth",
];

export interface WordCard {
  word: string;
  taboo: string[];
}

/**
 * Word-rush deck — 50 single-word cards, each with 5 forbidden words.
 * Curated taboo-style: the forbidden list blocks the five most natural
 * clues so every card takes real creativity.
 */
export const WORD_CARDS: WordCard[] = [
  { word: "Beach", taboo: ["sand", "ocean", "waves", "towel", "sun"] },
  { word: "Coffee", taboo: ["drink", "morning", "caffeine", "cup", "Starbucks"] },
  { word: "Pizza", taboo: ["cheese", "slice", "Italian", "pepperoni", "dough"] },
  { word: "Snow", taboo: ["cold", "white", "winter", "ski", "flake"] },
  { word: "Guitar", taboo: ["strings", "play", "music", "strum", "band"] },
  { word: "Airplane", taboo: ["fly", "wings", "pilot", "airport", "sky"] },
  { word: "Vampire", taboo: ["blood", "Dracula", "fangs", "bat", "night"] },
  { word: "Birthday", taboo: ["cake", "party", "candles", "age", "gift"] },
  { word: "Camera", taboo: ["photo", "picture", "lens", "click", "film"] },
  { word: "Dentist", taboo: ["teeth", "drill", "cavity", "floss", "doctor"] },
  { word: "Elevator", taboo: ["floor", "up", "down", "button", "stairs"] },
  { word: "Fireworks", taboo: ["explode", "sky", "July", "boom", "colors"] },
  { word: "Giraffe", taboo: ["neck", "tall", "animal", "zoo", "spots"] },
  { word: "Honey", taboo: ["bee", "sweet", "sticky", "jar", "Pooh"] },
  { word: "Igloo", taboo: ["ice", "snow", "cold", "dome", "Arctic"] },
  { word: "Jellyfish", taboo: ["sting", "ocean", "tentacle", "swim", "clear"] },
  { word: "Karate", taboo: ["martial", "kick", "belt", "chop", "fight"] },
  { word: "Lipstick", taboo: ["makeup", "red", "lips", "kiss", "tube"] },
  { word: "Mermaid", taboo: ["tail", "ocean", "Ariel", "fish", "swim"] },
  { word: "Ninja", taboo: ["sword", "sneak", "black", "Japan", "fight"] },
  { word: "Octopus", taboo: ["eight", "arms", "tentacle", "ink", "sea"] },
  { word: "Pancake", taboo: ["syrup", "breakfast", "flip", "flat", "batter"] },
  { word: "Rainbow", taboo: ["colors", "rain", "sky", "arc", "pot"] },
  { word: "Skateboard", taboo: ["wheels", "trick", "ride", "ramp", "ollie"] },
  { word: "Tornado", taboo: ["wind", "spin", "storm", "funnel", "Kansas"] },
  { word: "Umbrella", taboo: ["rain", "wet", "open", "handle", "cover"] },
  { word: "Volcano", taboo: ["lava", "erupt", "mountain", "hot", "ash"] },
  { word: "Waffle", taboo: ["breakfast", "syrup", "squares", "iron", "batter"] },
  { word: "Yoga", taboo: ["stretch", "pose", "mat", "breathe", "namaste"] },
  { word: "Zombie", taboo: ["dead", "brains", "walk", "apocalypse", "undead"] },
  { word: "Popcorn", taboo: ["movie", "kernel", "butter", "pop", "snack"] },
  { word: "Sunburn", taboo: ["red", "skin", "beach", "lotion", "peel"] },
  { word: "Karaoke", taboo: ["sing", "microphone", "songs", "bar", "lyrics"] },
  { word: "Tent", taboo: ["camp", "sleep", "poles", "outside", "pitch"] },
  { word: "Whale", taboo: ["ocean", "big", "blowhole", "mammal", "Moby"] },
  { word: "Cactus", taboo: ["desert", "spiky", "plant", "water", "prick"] },
  { word: "Chopsticks", taboo: ["eat", "sushi", "wood", "Asian", "utensil"] },
  { word: "Fireplace", taboo: ["warm", "logs", "chimney", "mantel", "burn"] },
  { word: "Hammock", taboo: ["swing", "relax", "trees", "nap", "rope"] },
  { word: "Lifeguard", taboo: ["pool", "save", "whistle", "beach", "swim"] },
  { word: "Magnet", taboo: ["attract", "fridge", "metal", "pull", "pole"] },
  { word: "Parachute", taboo: ["jump", "plane", "fall", "open", "skydive"] },
  { word: "Robot", taboo: ["machine", "metal", "beep", "program", "android"] },
  { word: "Sandcastle", taboo: ["beach", "build", "bucket", "tide", "moat"] },
  { word: "Scarecrow", taboo: ["corn", "field", "birds", "straw", "Oz"] },
  { word: "Snorkel", taboo: ["swim", "mask", "breathe", "tube", "reef"] },
  { word: "Squirrel", taboo: ["nuts", "tree", "tail", "acorn", "bushy"] },
  { word: "Suitcase", taboo: ["pack", "travel", "clothes", "wheels", "luggage"] },
  { word: "Telescope", taboo: ["stars", "look", "space", "lens", "zoom"] },
  { word: "Trampoline", taboo: ["jump", "bounce", "spring", "backyard", "flip"] },
];

export interface Chain {
  id: string;
  name: string;
}

/** Chains worth counting between San Diego and Vancouver. */
export const FASTFOOD_CHAINS: Chain[] = [
  { id: "mcd", name: "McDonald's" },
  { id: "sbux", name: "Starbucks" },
  { id: "innout", name: "In-N-Out" },
  { id: "cfa", name: "Chick-fil-A" },
  { id: "tbell", name: "Taco Bell" },
  { id: "wendys", name: "Wendy's" },
  { id: "bk", name: "Burger King" },
  { id: "subway", name: "Subway" },
  { id: "dutch", name: "Dutch Bros" },
  { id: "dq", name: "Dairy Queen" },
  { id: "jack", name: "Jack in the Box" },
  { id: "panda", name: "Panda Express" },
  { id: "timmys", name: "Tim Hortons" },
  { id: "aw", name: "A&W" },
];
