/** Static content for the road games. */

export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "Washington DC" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

export const CA_PROVINCES: { code: string; name: string }[] = [
  { code: "BC", name: "British Columbia" },
  { code: "AB", name: "Alberta" },
  { code: "SK", name: "Saskatchewan" },
  { code: "MB", name: "Manitoba" },
  { code: "ON", name: "Ontario" },
  { code: "QC", name: "Quebec" },
  { code: "NB", name: "New Brunswick" },
  { code: "NS", name: "Nova Scotia" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "NL", name: "Newfoundland" },
  { code: "YT", name: "Yukon" },
  { code: "NT", name: "Northwest Terr." },
  { code: "NU", name: "Nunavut" },
];

/** Scavenger-hunt targets — first to spot it claims it. */
export const ROADSIDE_ITEMS: string[] = [
  "Wind turbine",
  "Lighthouse",
  "Surfer in a wetsuit",
  "Sea lion or seal",
  "Whale spout",
  "Redwood bigger than the car",
  "Elk or deer",
  "Cow traffic jam",
  "Hawk on a fence post",
  "Vineyard",
  "Roadside fruit stand",
  "Classic car (pre-1980)",
  "Convertible with the top down",
  "RV towing a car",
  "Mattress on a roof",
  "Speed trap (cop with radar)",
  "Hitchhiker",
  "Rest-stop dog",
  "Train crossing",
  "Ferry boat",
  "Drawbridge",
  "Tunnel",
  "State line sign",
  "Border crossing booth",
];

export interface WordCard {
  word: string;
  taboo: string[];
}

/** Word-rush deck — describe the word without saying the forbidden ones. */
export const WORD_CARDS: WordCard[] = [
  { word: "Road trip", taboo: ["car", "drive", "travel", "vacation"] },
  { word: "Golden Gate Bridge", taboo: ["San Francisco", "red", "bay", "cross"] },
  { word: "Campfire", taboo: ["marshmallow", "wood", "flame", "smoke"] },
  { word: "Lighthouse", taboo: ["ocean", "light", "ship", "tower"] },
  { word: "Redwood", taboo: ["tree", "tall", "forest", "California"] },
  { word: "Surfing", taboo: ["wave", "board", "ocean", "beach"] },
  { word: "Tide pool", taboo: ["starfish", "ocean", "rock", "low"] },
  { word: "Motel", taboo: ["sleep", "hotel", "room", "highway"] },
  { word: "Gas station", taboo: ["fuel", "pump", "car", "fill"] },
  { word: "Speed limit", taboo: ["fast", "sign", "police", "mph"] },
  { word: "License plate", taboo: ["car", "state", "number", "metal"] },
  { word: "Seagull", taboo: ["bird", "beach", "fries", "fly"] },
  { word: "Sunscreen", taboo: ["burn", "beach", "lotion", "SPF"] },
  { word: "Ferry", taboo: ["boat", "car", "water", "cross"] },
  { word: "Vancouver", taboo: ["Canada", "city", "British Columbia", "north"] },
  { word: "Space Needle", taboo: ["Seattle", "tower", "tall", "view"] },
  { word: "Sasquatch", taboo: ["Bigfoot", "hairy", "forest", "monster"] },
  { word: "Otter", taboo: ["sea", "cute", "swim", "kelp"] },
  { word: "Trail mix", taboo: ["nuts", "raisins", "snack", "hike"] },
  { word: "Sleeping bag", taboo: ["camp", "warm", "zip", "tent"] },
  { word: "Windshield", taboo: ["glass", "wiper", "car", "bug"] },
  { word: "Pit stop", taboo: ["bathroom", "gas", "break", "stop"] },
  { word: "GPS", taboo: ["map", "directions", "navigate", "satellite"] },
  { word: "Podcast", taboo: ["listen", "episode", "show", "audio"] },
  { word: "Karaoke", taboo: ["sing", "song", "microphone", "lyrics"] },
  { word: "In-N-Out", taboo: ["burger", "fries", "California", "animal style"] },
  { word: "Food truck", taboo: ["eat", "street", "taco", "wheels"] },
  { word: "Clam chowder", taboo: ["soup", "bread bowl", "seafood", "creamy"] },
  { word: "Boardwalk", taboo: ["beach", "pier", "walk", "wood"] },
  { word: "Ferris wheel", taboo: ["ride", "round", "carnival", "spin"] },
  { word: "Hot spring", taboo: ["water", "warm", "soak", "natural"] },
  { word: "Waterfall", taboo: ["water", "fall", "cliff", "river"] },
  { word: "Fog", taboo: ["cloud", "gray", "see", "mist"] },
  { word: "Sunset", taboo: ["sun", "orange", "evening", "horizon"] },
  { word: "Full moon", taboo: ["night", "sky", "round", "wolf"] },
  { word: "Sand dollar", taboo: ["beach", "round", "shell", "white"] },
  { word: "Driftwood", taboo: ["beach", "wood", "wash", "log"] },
  { word: "Road snacks", taboo: ["eat", "chips", "drive", "hungry"] },
  { word: "Air freshener", taboo: ["smell", "tree", "mirror", "hang"] },
  { word: "Cruise control", taboo: ["speed", "button", "foot", "highway"] },
  { word: "Toll booth", taboo: ["pay", "road", "bridge", "money"] },
  { word: "Rest area", taboo: ["stop", "bathroom", "highway", "sleep"] },
  { word: "Scenic overlook", taboo: ["view", "pull over", "photo", "cliff"] },
  { word: "Souvenir", taboo: ["buy", "gift shop", "magnet", "remember"] },
  { word: "Postcard", taboo: ["mail", "send", "picture", "write"] },
  { word: "Polaroid", taboo: ["photo", "instant", "shake", "camera"] },
  { word: "Matching hoodies", taboo: ["wear", "couple", "same", "sweatshirt"] },
  { word: "Playlist", taboo: ["music", "songs", "Spotify", "queue"] },
];

export interface Chain {
  id: string;
  name: string;
}

/** Chains worth counting between San Diego and Vancouver. */
export const FASTFOOD_CHAINS: Chain[] = [
  { id: "mcd", name: "McDonald's" },
  { id: "sbux", name: "Starbucks" },
  { id: "innout", name: "In-N-Out" },
  { id: "cfa", name: "Chick-fil-A" },
  { id: "tbell", name: "Taco Bell" },
  { id: "wendys", name: "Wendy's" },
  { id: "bk", name: "Burger King" },
  { id: "subway", name: "Subway" },
  { id: "dutch", name: "Dutch Bros" },
  { id: "dq", name: "Dairy Queen" },
  { id: "jack", name: "Jack in the Box" },
  { id: "panda", name: "Panda Express" },
  { id: "timmys", name: "Tim Hortons" },
  { id: "aw", name: "A&W" },
];
